apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
        - name: chatbot-frontend
          image: 986611521344.dkr.ecr.ap-northeast-2.amazonaws.com/chatbot/frontend:36cae27e77f8d8b10b9bf1bb71e692860ced79ff
          ports:
            - containerPort: 5173
